### ISSUE TITLE
CDMI 2.0 Spec - Review May vs. Can

### ISSUE THREAD

**Issue by dslik** [SNIA/CDMI-spec#216]
The spec text needs to be reviewed to determine the use of "may" and "can".

**Comment by sbs-jms** [comment]
Many api summaries include:
> Request headers 
> ---------------
> Request headers can be provided as per RFC 2616 :cite:`rfc2616`.

Two questions: 
- Is this a "headers could be included in the request" (hence 'can') or "it is permissible to include headers in a request" (hence 'may')?
- More generally, would it make more sense to assert conformance to RFC 2616 more generally, and forego this content?

**Comment by sbs-jms** [comment]
- Not clear on can/may in the table cdmi_advanced/cdmi_exports.txt near line 210
- cdmi_advanced/cdmi_queue_object.txt 1197 et al; we talked about this before, but my notes are in my (now inaccessible) office
- preamble/overview.txt,
  - line 181: retaining 'can', since this appears introductory and not prescriptive. Generally, is this document constraining the client at all? That is, should "the client can" be "the client may" (i.e., the client is permitted to) or does it mean "key an eye on that sneaky client and be ready for them to "?
  - line 346: "the CDMI server functions": always? In this case? Is this a requirement?
  - line 86: ???

**Comment by dslik** [comment]
* Fixed exports.
* "A response body can be provided as per RFC 2616 :cite:`rfc2616`." will be left as "can".
*
